# Generated by Django 3.2.7 on 2021-09-21 18:33

import ctac.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaResidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_residence', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(default='', help_text='Enter any text', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_in', models.CharField(choices=[('present', 'present'), ('not_available', 'not_available')], max_length=20)),
                ('date', models.DateField(help_text='Enter the date of purchase', validators=[ctac.models.no_future])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapel_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', help_text='Enter any text', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChapelHeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapel_heads', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', help_text='Enter any text', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=5, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('second_name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(max_length=70)),
                ('contact_number', models.CharField(max_length=14)),
                ('owner_of_phone_number', models.CharField(choices=[('another person', 'another person'), ('self', 'self')], max_length=20)),
                ('details_of_owner', models.CharField(blank=True, max_length=200, verbose_name='If Phone Is For Another Person Then Provide Details')),
                ('whatsapp_number', models.CharField(blank=True, max_length=12)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('age', models.CharField(choices=[('60 and above', '60 and above'), ('30-39 years', '30-39 years'), ('50-59 years', '50-59 years'), ('20-29 years', '20-29 years'), ('40-49 years', '40-49 years'), ('10-19 years', '10-19 years')], max_length=15, verbose_name='Select your Age Group')),
                ('occupation', models.CharField(max_length=30, verbose_name='Your Profession')),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('widow', 'widow')], max_length=50)),
                ('micro_area_name', models.CharField(max_length=100)),
                ('nearest_landmark', models.CharField(max_length=100)),
                ('phone_usage', models.CharField(choices=[("I don't have a smartphone but i have a yam", "I don't have a smartphone but i have a yam"), ('I use a tablet for online service', 'I use a tablet for online service'), ("I don't have a phone", "I don't have a phone"), ('I use a smartphone for online service', 'I use a smartphone for online service')], max_length=50, verbose_name='Which of The Following Applies To You')),
                ('online_service', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=50, verbose_name='Are You Able To Join Our Online Services?')),
                ('state', models.CharField(choices=[('Shepherd', 'Shepherd'), ('Ministry Shepherd', 'Ministry Shepherd'), ('Member', 'Member'), ("Don't Understand", "Don't Understand"), ('Assisting Shepherd or Trainee Shepherd', 'Assisting Shepherd or Trainee Shepherd')], max_length=100, verbose_name='Please Tick Where Applicable')),
                ('bacenta_leader', models.CharField(blank=True, max_length=50, verbose_name='Name of Your Bacenta Leader. (Answer Only If Applicable')),
                ('slug', models.SlugField(default='', help_text='Enter any text', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', help_text='Enter any text', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('second_name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(max_length=70)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('title', models.CharField(choices=[('Bishop', 'Bishop'), ('Ps', 'Ps'), ('Rev', 'Rev')], max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('slug', models.SlugField(default='', help_text='Enter any text', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', help_text='Enter any text', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shepherd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('second_name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(max_length=70)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('gps_address', models.CharField(blank=True, max_length=15)),
                ('type', models.CharField(choices=[('Assistant Shepherd', 'Assistant Shepherd'), ('Ministry Shepherd', 'Ministry Shepherd'), ('Trainee Shepherd', 'Trainee Shepherd'), ('Bacenta Leader', 'Bacenta Leader')], max_length=30, verbose_name='Type of Shepherd')),
                ('slug', models.SlugField(default='', help_text='Enter any text', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ctac.chapel')),
                ('ministry', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ctac.ministry')),
            ],
        ),
    ]
