# Generated by Django 2.1.7 on 2021-11-22 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shepherd',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pastor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ministry',
            name='chapel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ctac.Chapel'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='area_of_residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctac.AreaResidence'),
        ),
        migrations.AddField(
            model_name='member',
            name='chapel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctac.Chapel'),
        ),
        migrations.AddField(
            model_name='member',
            name='chapel_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctac.ChapelHeads'),
        ),
        migrations.AddField(
            model_name='member',
            name='ministries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctac.Ministry'),
        ),
        migrations.AddField(
            model_name='member',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctac.Service'),
        ),
        migrations.AddField(
            model_name='member',
            name='shepherd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctac.Shepherd'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='code',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapelheads',
            name='chapel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctac.Chapel'),
        ),
        migrations.AddField(
            model_name='chapelheads',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancemember',
            name='chapel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctac.Chapel'),
        ),
        migrations.AddField(
            model_name='attendancemember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctac.Member'),
        ),
        migrations.AddField(
            model_name='attendancemember',
            name='services',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='ctac.Service'),
        ),
        migrations.AddField(
            model_name='attendancemember',
            name='shepherd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctac.Shepherd'),
        ),
        migrations.AddField(
            model_name='attendancemember',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arearesidence',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
