# Generated by Django 3.2.4 on 2021-07-29 20:29

import ctac.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctac', '0002_auto_20210727_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemember',
            name='date',
            field=models.DateField(help_text='Enter the date of purchase', validators=[ctac.models.no_future]),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.CharField(choices=[('20-29 years', '20-29 years'), ('60 and above', '60 and above'), ('10-19 years', '10-19 years'), ('50-59 years', '50-59 years'), ('40-49 years', '40-49 years'), ('30-39 years', '30-39 years')], max_length=15, verbose_name='Select your Age Group'),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('widow', 'widow'), ('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='owner_of_phone_number',
            field=models.CharField(choices=[('self', 'self'), ('another person', 'another person')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_usage',
            field=models.CharField(choices=[('I use a tablet for online service', 'I use a tablet for online service'), ("I don't have a smartphone but i have a yam", "I don't have a smartphone but i have a yam"), ("I don't have a phone", "I don't have a phone"), ('I use a smartphone for online service', 'I use a smartphone for online service')], max_length=50, verbose_name='Which of The Following Applies To You'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='state',
            field=models.CharField(choices=[('Shepherd', 'Shepherd'), ("Don't Understand", "Don't Understand"), ('Assisting Shepherd or Trainee Shepherd', 'Assisting Shepherd or Trainee Shepherd'), ('Ministry Shepherd', 'Ministry Shepherd'), ('Member', 'Member')], max_length=100, verbose_name='Please Tick Where Applicable'),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='title',
            field=models.CharField(choices=[('Bishop', 'Bishop'), ('Rev', 'Rev'), ('Ps', 'Ps')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shepherd',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shepherd',
            name='type',
            field=models.CharField(choices=[('Ministry Shepherd', 'Ministry Shepherd'), ('Assistant Shepherd', 'Assistant Shepherd'), ('Trainee Shepherd', 'Trainee Shepherd'), ('Bacenta Leader', 'Bacenta Leader')], max_length=30, verbose_name='Type of Shepherd'),
        ),
    ]
