# Generated by Django 3.2.6 on 2021-09-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctac', '0002_auto_20210902_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemember',
            name='present_in',
            field=models.CharField(choices=[('not_available', 'not_available'), ('present', 'present')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.CharField(choices=[('10-19 years', '10-19 years'), ('50-59 years', '50-59 years'), ('30-39 years', '30-39 years'), ('20-29 years', '20-29 years'), ('60 and above', '60 and above'), ('40-49 years', '40-49 years')], max_length=15, verbose_name='Select your Age Group'),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('widow', 'widow'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='owner_of_phone_number',
            field=models.CharField(choices=[('another person', 'another person'), ('self', 'self')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_usage',
            field=models.CharField(choices=[("I don't have a smartphone but i have a yam", "I don't have a smartphone but i have a yam"), ('I use a tablet for online service', 'I use a tablet for online service'), ("I don't have a phone", "I don't have a phone"), ('I use a smartphone for online service', 'I use a smartphone for online service')], max_length=50, verbose_name='Which of The Following Applies To You'),
        ),
        migrations.AlterField(
            model_name='member',
            name='state',
            field=models.CharField(choices=[('Member', 'Member'), ('Ministry Shepherd', 'Ministry Shepherd'), ("Don't Understand", "Don't Understand"), ('Shepherd', 'Shepherd'), ('Assisting Shepherd or Trainee Shepherd', 'Assisting Shepherd or Trainee Shepherd')], max_length=100, verbose_name='Please Tick Where Applicable'),
        ),
        migrations.AlterField(
            model_name='shepherd',
            name='type',
            field=models.CharField(choices=[('Ministry Shepherd', 'Ministry Shepherd'), ('Assistant Shepherd', 'Assistant Shepherd'), ('Bacenta Leader', 'Bacenta Leader'), ('Trainee Shepherd', 'Trainee Shepherd')], max_length=30, verbose_name='Type of Shepherd'),
        ),
        migrations.DeleteModel(
            name='Pastor',
        ),
    ]
