# Generated by Django 3.2.6 on 2021-09-02 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctac', '0003_auto_20210902_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.CharField(choices=[('50-59 years', '50-59 years'), ('60 and above', '60 and above'), ('20-29 years', '20-29 years'), ('40-49 years', '40-49 years'), ('30-39 years', '30-39 years'), ('10-19 years', '10-19 years')], max_length=15, verbose_name='Select your Age Group'),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('widow', 'widow'), ('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='owner_of_phone_number',
            field=models.CharField(choices=[('self', 'self'), ('another person', 'another person')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_usage',
            field=models.CharField(choices=[('I use a smartphone for online service', 'I use a smartphone for online service'), ('I use a tablet for online service', 'I use a tablet for online service'), ("I don't have a smartphone but i have a yam", "I don't have a smartphone but i have a yam"), ("I don't have a phone", "I don't have a phone")], max_length=50, verbose_name='Which of The Following Applies To You'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='state',
            field=models.CharField(choices=[("Don't Understand", "Don't Understand"), ('Assisting Shepherd or Trainee Shepherd', 'Assisting Shepherd or Trainee Shepherd'), ('Ministry Shepherd', 'Ministry Shepherd'), ('Shepherd', 'Shepherd'), ('Member', 'Member')], max_length=100, verbose_name='Please Tick Where Applicable'),
        ),
        migrations.AlterField(
            model_name='shepherd',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shepherd',
            name='type',
            field=models.CharField(choices=[('Trainee Shepherd', 'Trainee Shepherd'), ('Bacenta Leader', 'Bacenta Leader'), ('Ministry Shepherd', 'Ministry Shepherd'), ('Assistant Shepherd', 'Assistant Shepherd')], max_length=30, verbose_name='Type of Shepherd'),
        ),
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('second_name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(max_length=70)),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20)),
                ('title', models.CharField(choices=[('Rev', 'Rev'), ('Ps', 'Ps'), ('Bishop', 'Bishop')], max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('slug', models.SlugField(default='', help_text='Enter any text', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
