# Generated by Django 3.2.7 on 2021-09-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctac', '0003_auto_20210921_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.CharField(choices=[('50-59 years', '50-59 years'), ('30-39 years', '30-39 years'), ('60 and above', '60 and above'), ('10-19 years', '10-19 years'), ('20-29 years', '20-29 years'), ('40-49 years', '40-49 years')], max_length=15, verbose_name='Select your Age Group'),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('widow', 'widow'), ('Married', 'Married'), ('Single', 'Single')], max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='owner_of_phone_number',
            field=models.CharField(choices=[('self', 'self'), ('another person', 'another person')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_usage',
            field=models.CharField(choices=[('I use a smartphone for online service', 'I use a smartphone for online service'), ("I don't have a phone", "I don't have a phone"), ("I don't have a smartphone but i have a yam", "I don't have a smartphone but i have a yam"), ('I use a tablet for online service', 'I use a tablet for online service')], max_length=50, verbose_name='Which of The Following Applies To You'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='state',
            field=models.CharField(choices=[('Member', 'Member'), ('Ministry Shepherd', 'Ministry Shepherd'), ('Assisting Shepherd or Trainee Shepherd', 'Assisting Shepherd or Trainee Shepherd'), ("Don't Understand", "Don't Understand"), ('Shepherd', 'Shepherd')], max_length=100, verbose_name='Please Tick Where Applicable'),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='title',
            field=models.CharField(choices=[('Rev', 'Rev'), ('Ps', 'Ps'), ('Bishop', 'Bishop')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shepherd',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shepherd',
            name='type',
            field=models.CharField(choices=[('Bacenta Leader', 'Bacenta Leader'), ('Ministry Shepherd', 'Ministry Shepherd'), ('Assistant Shepherd', 'Assistant Shepherd'), ('Trainee Shepherd', 'Trainee Shepherd')], max_length=30, verbose_name='Type of Shepherd'),
        ),
    ]
