# Generated by Django 3.2.4 on 2021-10-27 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctac', '0008_auto_20210923_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arearesidence',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancemember',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapelheads',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.CharField(choices=[('50-59 years', '50-59 years'), ('10-19 years', '10-19 years'), ('30-39 years', '30-39 years'), ('40-49 years', '40-49 years'), ('60 and above', '60 and above'), ('20-29 years', '20-29 years')], max_length=15, verbose_name='Select your Age Group'),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Single', 'Single'), ('widow', 'widow'), ('Married', 'Married')], max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='online_service',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=50, verbose_name='Are You Able To Join Our Online Services?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_usage',
            field=models.CharField(choices=[('I use a smartphone for online service', 'I use a smartphone for online service'), ('I use a tablet for online service', 'I use a tablet for online service'), ("I don't have a phone", "I don't have a phone"), ("I don't have a smartphone but i have a yam", "I don't have a smartphone but i have a yam")], max_length=50, verbose_name='Which of The Following Applies To You'),
        ),
        migrations.AlterField(
            model_name='member',
            name='state',
            field=models.CharField(choices=[('Ministry Shepherd', 'Ministry Shepherd'), ('Member', 'Member'), ('Assisting Shepherd or Trainee Shepherd', 'Assisting Shepherd or Trainee Shepherd'), ('Shepherd', 'Shepherd'), ("Don't Understand", "Don't Understand")], max_length=100, verbose_name='Please Tick Where Applicable'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='title',
            field=models.CharField(choices=[('Bishop', 'Bishop'), ('Rev', 'Rev'), ('Ps', 'Ps')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shepherd',
            name='type',
            field=models.CharField(choices=[('Ministry Shepherd', 'Ministry Shepherd'), ('Trainee Shepherd', 'Trainee Shepherd'), ('Bacenta Leader', 'Bacenta Leader'), ('Assistant Shepherd', 'Assistant Shepherd')], max_length=30, verbose_name='Type of Shepherd'),
        ),
        migrations.AlterField(
            model_name='shepherd',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
