# Generated by Django 3.2.7 on 2021-09-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctac', '0010_auto_20210908_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='shepherd',
            name='chapel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ctac.chapel'),
        ),
        migrations.AddField(
            model_name='shepherd',
            name='ministry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ctac.ministry'),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.CharField(choices=[('10-19 years', '10-19 years'), ('20-29 years', '20-29 years'), ('60 and above', '60 and above'), ('40-49 years', '40-49 years'), ('30-39 years', '30-39 years'), ('50-59 years', '50-59 years')], max_length=15, verbose_name='Select your Age Group'),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('widow', 'widow'), ('Single', 'Single'), ('Divorced', 'Divorced')], max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='online_service',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, verbose_name='Are You Able To Join Our Online Services?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='state',
            field=models.CharField(choices=[('Shepherd', 'Shepherd'), ('Assisting Shepherd or Trainee Shepherd', 'Assisting Shepherd or Trainee Shepherd'), ('Ministry Shepherd', 'Ministry Shepherd'), ("Don't Understand", "Don't Understand"), ('Member', 'Member')], max_length=100, verbose_name='Please Tick Where Applicable'),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='title',
            field=models.CharField(choices=[('Ps', 'Ps'), ('Bishop', 'Bishop'), ('Rev', 'Rev')], max_length=30),
        ),
        migrations.AlterField(
            model_name='shepherd',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shepherd',
            name='type',
            field=models.CharField(choices=[('Trainee Shepherd', 'Trainee Shepherd'), ('Assistant Shepherd', 'Assistant Shepherd'), ('Bacenta Leader', 'Bacenta Leader'), ('Ministry Shepherd', 'Ministry Shepherd')], max_length=30, verbose_name='Type of Shepherd'),
        ),
    ]
